/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db;

import com.sun.java.swing.plaf.motif.MotifLookAndFeel;
import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.PrintJob;
import java.util.Properties;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.plaf.metal.MetalLookAndFeel;

/**
 *
 * @author Agile
 */
public class Inventory extends javax.swing.JFrame {

    /**
     * Creates new form Inventory
     */
    public Inventory(String uid,String mode) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("HELLO "+uid.toUpperCase()+", WELCOME TO INVENTORY MANAGEMENT SYSTEM");
        if(mode.equals("Emp"))
            rpt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        print = new javax.swing.JMenuItem();
        ext = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        masterform = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        masterreport = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        custadd = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        updcust = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        delcust = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        searchcust = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        listcust = new javax.swing.JMenuItem();
        sm = new javax.swing.JMenu();
        addsm = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        usm = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        dsm = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        reportsm = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        purItem = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        editpurchase = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        returnpurchase = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        listofallpurchase = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        saleform = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        saleupdate = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        salereturn = new javax.swing.JMenuItem();
        jSeparator21 = new javax.swing.JPopupMenu.Separator();
        salesreport = new javax.swing.JMenuItem();
        rpt = new javax.swing.JMenu();
        salemnthrpt = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        saleyearrpt = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        purmnthrpt = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        puryearrpt = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        winLF = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        winCLF = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        motifLF = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        MetalLF = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        NimLF = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(40, 40, 0, 0));

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1236, Short.MAX_VALUE)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jMenu6.setMnemonic('f');
        jMenu6.setText("File");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        print.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        print.setMnemonic('p');
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jMenu6.add(print);

        ext.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        ext.setMnemonic('x');
        ext.setText("Exit");
        jMenu6.add(ext);

        jMenuBar1.add(jMenu6);

        jMenu1.setMnemonic('p');
        jMenu1.setText("Product");

        masterform.setMnemonic('m');
        masterform.setText("Master Form");
        masterform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterformActionPerformed(evt);
            }
        });
        jMenu1.add(masterform);
        jMenu1.add(jSeparator4);

        masterreport.setMnemonic('r');
        masterreport.setText("Master Product Report");
        masterreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterreportActionPerformed(evt);
            }
        });
        jMenu1.add(masterreport);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('c');
        jMenu2.setText("Customer");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        custadd.setMnemonic('a');
        custadd.setText("Add New Customer");
        custadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custaddActionPerformed(evt);
            }
        });
        jMenu2.add(custadd);
        jMenu2.add(jSeparator12);

        updcust.setMnemonic('u');
        updcust.setText("Update Existing Customer");
        updcust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updcustActionPerformed(evt);
            }
        });
        jMenu2.add(updcust);
        jMenu2.add(jSeparator13);

        delcust.setMnemonic('d');
        delcust.setText("Delete Existing Customer");
        delcust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delcustActionPerformed(evt);
            }
        });
        jMenu2.add(delcust);
        jMenu2.add(jSeparator14);

        searchcust.setMnemonic('s');
        searchcust.setText("Search Existing Customer");
        searchcust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchcustActionPerformed(evt);
            }
        });
        jMenu2.add(searchcust);
        jMenu2.add(jSeparator15);

        listcust.setMnemonic('l');
        listcust.setText("List of All Customer");
        listcust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listcustActionPerformed(evt);
            }
        });
        jMenu2.add(listcust);

        jMenuBar1.add(jMenu2);

        sm.setMnemonic('s');
        sm.setText("SalesMan");
        sm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smActionPerformed(evt);
            }
        });

        addsm.setMnemonic('a');
        addsm.setText("Add Salesman");
        addsm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsmActionPerformed(evt);
            }
        });
        sm.add(addsm);
        sm.add(jSeparator1);

        usm.setMnemonic('u');
        usm.setText("Update Salesman");
        usm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usmActionPerformed(evt);
            }
        });
        sm.add(usm);
        sm.add(jSeparator2);

        dsm.setMnemonic('d');
        dsm.setText("Delete Salesman");
        dsm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsmActionPerformed(evt);
            }
        });
        sm.add(dsm);
        sm.add(jSeparator3);

        reportsm.setMnemonic('l');
        reportsm.setText("List of All Salesman");
        reportsm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsmActionPerformed(evt);
            }
        });
        sm.add(reportsm);

        jMenuBar1.add(sm);

        jMenu4.setMnemonic('r');
        jMenu4.setText("Purchase");

        purItem.setMnemonic('p');
        purItem.setText("Purchase Item");
        purItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purItemActionPerformed(evt);
            }
        });
        jMenu4.add(purItem);
        jMenu4.add(jSeparator9);

        editpurchase.setMnemonic('e');
        editpurchase.setText("Edit Purchase");
        editpurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editpurchaseActionPerformed(evt);
            }
        });
        jMenu4.add(editpurchase);
        jMenu4.add(jSeparator10);

        returnpurchase.setMnemonic('r');
        returnpurchase.setText("Return Item");
        returnpurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnpurchaseActionPerformed(evt);
            }
        });
        jMenu4.add(returnpurchase);
        jMenu4.add(jSeparator11);

        listofallpurchase.setMnemonic('l');
        listofallpurchase.setText("List of All Purchase");
        listofallpurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listofallpurchaseActionPerformed(evt);
            }
        });
        jMenu4.add(listofallpurchase);

        jMenuBar1.add(jMenu4);

        jMenu5.setMnemonic('l');
        jMenu5.setText("Sales");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        saleform.setMnemonic('p');
        saleform.setText("Product Sale form");
        saleform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleformActionPerformed(evt);
            }
        });
        jMenu5.add(saleform);
        jMenu5.add(jSeparator7);

        saleupdate.setMnemonic('u');
        saleupdate.setText("Sale Update Form");
        saleupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleupdateActionPerformed(evt);
            }
        });
        jMenu5.add(saleupdate);
        jMenu5.add(jSeparator20);

        salereturn.setMnemonic('r');
        salereturn.setText("Product Sale Return Form");
        salereturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salereturnActionPerformed(evt);
            }
        });
        jMenu5.add(salereturn);
        jMenu5.add(jSeparator21);

        salesreport.setMnemonic('s');
        salesreport.setText("Sales Report");
        salesreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesreportActionPerformed(evt);
            }
        });
        jMenu5.add(salesreport);

        jMenuBar1.add(jMenu5);

        rpt.setMnemonic('r');
        rpt.setText("Report");

        salemnthrpt.setText("Monthly Product Sales Report");
        salemnthrpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salemnthrptActionPerformed(evt);
            }
        });
        rpt.add(salemnthrpt);
        rpt.add(jSeparator5);

        saleyearrpt.setText("Yearly Product Sales Report");
        saleyearrpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleyearrptActionPerformed(evt);
            }
        });
        rpt.add(saleyearrpt);
        rpt.add(jSeparator6);

        purmnthrpt.setText("Monthly Product Purchase Report");
        purmnthrpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purmnthrptActionPerformed(evt);
            }
        });
        rpt.add(purmnthrpt);
        rpt.add(jSeparator8);

        puryearrpt.setText("Yearly Product Purchase Report");
        puryearrpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puryearrptActionPerformed(evt);
            }
        });
        rpt.add(puryearrpt);

        jMenuBar1.add(rpt);

        jMenu3.setMnemonic('t');
        jMenu3.setText("Tools");

        winLF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        winLF.setMnemonic('w');
        winLF.setText("Windows Look And Feel ");
        winLF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winLFActionPerformed(evt);
            }
        });
        jMenu3.add(winLF);
        jMenu3.add(jSeparator16);

        winCLF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        winCLF.setMnemonic('c');
        winCLF.setText("Windows Clasic Look And Feel");
        winCLF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winCLFActionPerformed(evt);
            }
        });
        jMenu3.add(winCLF);
        jMenu3.add(jSeparator17);

        motifLF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        motifLF.setMnemonic('m');
        motifLF.setText("Motif Look And Feel");
        motifLF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motifLFActionPerformed(evt);
            }
        });
        jMenu3.add(motifLF);
        jMenu3.add(jSeparator18);

        MetalLF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        MetalLF.setMnemonic('w');
        MetalLF.setText("Metal Look And Feel");
        MetalLF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetalLFActionPerformed(evt);
            }
        });
        jMenu3.add(MetalLF);
        jMenu3.add(jSeparator19);

        NimLF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        NimLF.setMnemonic('n');
        NimLF.setText("Nimbus Look And Feel");
        NimLF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NimLFActionPerformed(evt);
            }
        });
        jMenu3.add(NimLF);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addsmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsmActionPerformed
       SMInternal si = new SMInternal(0);
       dp.add(si);
    }//GEN-LAST:event_addsmActionPerformed

    private void smActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smActionPerformed
   
    }//GEN-LAST:event_smActionPerformed

    private void dsmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsmActionPerformed
       SMInternal si = new SMInternal(1);
       dp.add(si);
   
    }//GEN-LAST:event_dsmActionPerformed

    private void usmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usmActionPerformed
       SMInternal si = new SMInternal(1);
       dp.add(si);

    }//GEN-LAST:event_usmActionPerformed

    private void purItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purItemActionPerformed
       PFInternal si = new PFInternal(0);
       dp.add(si);

    }//GEN-LAST:event_purItemActionPerformed

    private void editpurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editpurchaseActionPerformed
       PFInternal si = new PFInternal(1);
       dp.add(si);
    }//GEN-LAST:event_editpurchaseActionPerformed

    private void returnpurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnpurchaseActionPerformed
       PFInternal si = new PFInternal(1);
       dp.add(si);

    }//GEN-LAST:event_returnpurchaseActionPerformed

    private void custaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custaddActionPerformed
       CFInternal ci = new CFInternal(0);
       dp.add(ci);

    }//GEN-LAST:event_custaddActionPerformed

    private void listcustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listcustActionPerformed
       CustReport cr = new CustReport();
       dp.add(cr);

    }//GEN-LAST:event_listcustActionPerformed

    private void delcustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delcustActionPerformed
       CFInternal ci = new CFInternal(1);
       dp.add(ci);

    }//GEN-LAST:event_delcustActionPerformed

    private void searchcustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchcustActionPerformed
       CFInternal ci = new CFInternal(1);
       dp.add(ci);

    }//GEN-LAST:event_searchcustActionPerformed

    private void updcustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updcustActionPerformed
       CFInternal ci = new CFInternal(1);
       dp.add(ci);
    }//GEN-LAST:event_updcustActionPerformed

    private void saleupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleupdateActionPerformed
       SFInternal si = new SFInternal(1);
       dp.add(si);
    }//GEN-LAST:event_saleupdateActionPerformed

    private void saleformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleformActionPerformed
       SFInternal si = new SFInternal(0);
       dp.add(si);
 
    }//GEN-LAST:event_saleformActionPerformed

    private void salereturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salereturnActionPerformed
       SFInternal si = new SFInternal(1);
       dp.add(si);

    }//GEN-LAST:event_salereturnActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void reportsmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsmActionPerformed
       SalesmanReport cr = new SalesmanReport();
       dp.add(cr);

    }//GEN-LAST:event_reportsmActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void salesreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesreportActionPerformed
       SalesReport cr = new SalesReport();
       dp.add(cr);
 
    }//GEN-LAST:event_salesreportActionPerformed

    private void listofallpurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listofallpurchaseActionPerformed
       PurchaseReport r = new PurchaseReport();
       dp.add(r);
    }//GEN-LAST:event_listofallpurchaseActionPerformed

    private void masterreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterreportActionPerformed
       MasterReport r = new MasterReport();
       dp.add(r);
    }//GEN-LAST:event_masterreportActionPerformed

    private void masterformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterformActionPerformed
       MFInternal si = new MFInternal();
       dp.add(si);

    }//GEN-LAST:event_masterformActionPerformed

    private void winLFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winLFActionPerformed
       try
       {
           WindowsLookAndFeel w = new WindowsLookAndFeel();
           UIManager.setLookAndFeel(w);
           SwingUtilities.updateComponentTreeUI(this); // for screen refresh. 
       }catch(Exception ex){}
    }//GEN-LAST:event_winLFActionPerformed

    private void winCLFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winCLFActionPerformed
       try
       {
           UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
           SwingUtilities.updateComponentTreeUI(this); // for screen refresh. 
       }catch(Exception ex){}
    }//GEN-LAST:event_winCLFActionPerformed

    private void motifLFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motifLFActionPerformed
       try
       {
           UIManager.setLookAndFeel(new MotifLookAndFeel());
           SwingUtilities.updateComponentTreeUI(this); // for screen refresh. 
       }catch(Exception ex){}
    }//GEN-LAST:event_motifLFActionPerformed

    private void MetalLFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetalLFActionPerformed
       try
       {
           UIManager.setLookAndFeel(new MetalLookAndFeel());
           SwingUtilities.updateComponentTreeUI(this); // for screen refresh. 
       }catch(Exception ex){}
    }//GEN-LAST:event_MetalLFActionPerformed

    private void NimLFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NimLFActionPerformed
          try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
           } catch (Exception ex) {}
          
    }//GEN-LAST:event_NimLFActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
       dispose();
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
       try
       {
         Properties prop = new Properties();
         PrintJob pj = getToolkit().getPrintJob(this,"Inventory Print Slip", prop);
         printAll(pj.getGraphics()); // print all contents on printer Graphics. 
         pj.end(); // end the print poj after print the document.
       }
       catch(Exception ex) {}
    }//GEN-LAST:event_printActionPerformed

    private void salemnthrptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salemnthrptActionPerformed
       SalesYearlyReport r = new SalesYearlyReport();
       dp.add(r);
 
    }//GEN-LAST:event_salemnthrptActionPerformed

    private void purmnthrptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purmnthrptActionPerformed
       PurchaseYearlyReport r = new PurchaseYearlyReport();
       dp.add(r);
    }//GEN-LAST:event_purmnthrptActionPerformed

    private void puryearrptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puryearrptActionPerformed
       PurchaseYearlyReport r = new PurchaseYearlyReport();
       dp.add(r);
    }//GEN-LAST:event_puryearrptActionPerformed

    private void saleyearrptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleyearrptActionPerformed
       SalesYearlyReport r = new SalesYearlyReport();
       dp.add(r);
    }//GEN-LAST:event_saleyearrptActionPerformed
    class MasterReport extends JInternalFrame
    {
        MasterReport() 
        {        
            add(new MasterReportPanel());
            setTitle("Master Product Report.");
            setBounds(10,100,Inventory.this.getWidth()-30,500);
                            // Parent.currentobject.width - Inverntory Frame width.
            setVisible(true);
            setClosable(true); // for close
            setMaximizable(true); // for maximize 
            setIconifiable(true); // for minimize
        }
    }    
    
    class CustReport extends JInternalFrame
    {

        public CustReport() {
            add(new CustomerReportPanel());
            setTitle("Customer Report.");
            setBounds(10,100,Inventory.this.getWidth()-30,500);
                            // Parent.currentobject.width - Inverntory Frame width.
            setVisible(true);
            setClosable(true); // for close
            setMaximizable(true); // for maximize 
            setIconifiable(true); // for minimize
        }
    }    
    class SalesmanReport extends JInternalFrame
    {

        public SalesmanReport() {
           add(new SalesmanReportPanel());
           setTitle("Salesman Report.");
           setBounds(10,100,Inventory.this.getWidth()-30,500);
                            // Parent.currentobject.width - Inverntory Frame width.
            setVisible(true);
            setClosable(true); // for close
            setMaximizable(true); // for maximize 
            setIconifiable(true); // for minimize
        }
    }    
    class PurchaseReport extends JInternalFrame
    {

        public PurchaseReport() {
           add(new PurchaseReportPanel());
           setTitle("Purchase Report.");
           setBounds(10,100,Inventory.this.getWidth()-30,500);
                            // Parent.currentobject.width - Inverntory Frame width.
            setVisible(true);
            setClosable(true); // for close
            setMaximizable(true); // for maximize 
            setIconifiable(true); // for minimize
        }
    }    
    class PurchaseYearlyReport extends JInternalFrame
    {

        public PurchaseYearlyReport() {
           add(new PurchaseYearlyReportPanel());
           setTitle("Purchase Monthly & Yearly Report.");
           setBounds(10,100,Inventory.this.getWidth()-30,500);
                            // Parent.currentobject.width - Inverntory Frame width.
            setVisible(true);
            setClosable(true); // for close
            setMaximizable(true); // for maximize 
            setIconifiable(true); // for minimize
        }
    }   
    class SalesYearlyReport extends JInternalFrame
    {

        public SalesYearlyReport() {
           add(new db.SalesYearlyReportPanel());
           setTitle("Sales Monthly & Yearly Report.");
           setBounds(10,100,Inventory.this.getWidth()-30,500);
                            // Parent.currentobject.width - Inverntory Frame width.
            setVisible(true);
            setClosable(true); // for close
            setMaximizable(true); // for maximize 
            setIconifiable(true); // for minimize
        }
    }   
    
    class SalesReport extends JInternalFrame
    {

        public SalesReport() {
           add(new SalesReportPanel());
           setTitle("Sales Report.");
           setBounds(10,100,Inventory.this.getWidth()-30,500);
                            // Parent.currentobject.width - Inverntory Frame width.
            setVisible(true);
            setClosable(true); // for close
            setMaximizable(true); // for maximize 
            setIconifiable(true); // for minimize
        }
    }    
    class MFInternal extends JInternalFrame
    {

        public MFInternal() {
           add(new MasterPanel(this));
           setTitle("Master Form");
           setBounds(100,20,700,500);
            setVisible(true);
            setClosable(true); // for close
         //   setMaximizable(true); // for maximize 
            setIconifiable(true); // for minimize
        }
    }    
    class SFInternal extends JInternalFrame
    {

        public SFInternal(int x) {
           add(new SalesPanel(x,this));
           setTitle("Sales Form");
           setBounds(250,20,650,550);
            setVisible(true);
            setClosable(true); // for close
         //   setMaximizable(true); // for maximize 
            setIconifiable(true); // for minimize
        }
    }    
    class PFInternal extends JInternalFrame
    {

        public PFInternal(int x) {
           add(new PurchasePanel(x,this)); // this - pass current internal Frame. 
           setTitle("Purchase Form");
           setBounds(250,20,650,600);
            setVisible(true);
            setClosable(true); // for close
          //  setMaximizable(true); // for maximize 
            setIconifiable(true); // for minimize
        }
    }    
    class SMInternal extends JInternalFrame
    {

        public SMInternal(int x) {
           add(new SalesManPanel(x,this));
           setTitle("Salesman Form");
           setBounds(250,40,600,450);
            setVisible(true);
            setClosable(true); // for close
          //  setMaximizable(true); // for maximize 
            setIconifiable(true); // for minimize
        }
        
    }
   class CFInternal extends JInternalFrame
    {

        public CFInternal(int x) {
           add(new CustomerPanel(x,this));
           setTitle("Purchase Form");
           setBounds(100,20,650,550);
            setVisible(true);
            setClosable(true); // for close
          //  setMaximizable(true); // for maximize 
            setIconifiable(true); // for minimize
        }
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MetalLF;
    private javax.swing.JMenuItem NimLF;
    private javax.swing.JMenuItem addsm;
    private javax.swing.JMenuItem custadd;
    private javax.swing.JMenuItem delcust;
    private javax.swing.JDesktopPane dp;
    private javax.swing.JMenuItem dsm;
    private javax.swing.JMenuItem editpurchase;
    private javax.swing.JMenuItem ext;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator21;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem listcust;
    private javax.swing.JMenuItem listofallpurchase;
    private javax.swing.JMenuItem masterform;
    private javax.swing.JMenuItem masterreport;
    private javax.swing.JMenuItem motifLF;
    private javax.swing.JMenuItem print;
    private javax.swing.JMenuItem purItem;
    private javax.swing.JMenuItem purmnthrpt;
    private javax.swing.JMenuItem puryearrpt;
    private javax.swing.JMenuItem reportsm;
    private javax.swing.JMenuItem returnpurchase;
    private javax.swing.JMenu rpt;
    private javax.swing.JMenuItem saleform;
    private javax.swing.JMenuItem salemnthrpt;
    private javax.swing.JMenuItem salereturn;
    private javax.swing.JMenuItem salesreport;
    private javax.swing.JMenuItem saleupdate;
    private javax.swing.JMenuItem saleyearrpt;
    private javax.swing.JMenuItem searchcust;
    private javax.swing.JMenu sm;
    private javax.swing.JMenuItem updcust;
    private javax.swing.JMenuItem usm;
    private javax.swing.JMenuItem winCLF;
    private javax.swing.JMenuItem winLF;
    // End of variables declaration//GEN-END:variables
}
