/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db;

import java.sql.ResultSet;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Agile
 */
public class SalesPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesPanel
     */
    JInternalFrame inter;
    int prevqty,updqty,currqty,maxqty;
    public SalesPanel(int x,JInternalFrame inter) {
        initComponents();
        this.inter = inter;
        total.setEditable(false);
        paid.setEditable(false);
        price.setEditable(false);
        try
        {
           ResultSet rs = Admin.getSalesProdId();
           prid.addItem("Select Product Id");
           while(rs.next())
           {
              prid.addItem(rs.getString(1)+" - "+rs.getString(2));
           }
           rs = Admin.getSalesCustId();
           custid.addItem("Select Customer Id");
           while(rs.next())
           {
              custid.addItem(rs.getString(1)+" - "+rs.getString(2));
           }
        }catch(Exception ex){}
        getSidList();
        if(x==0)
        {
           total.setEditable(false);
           lblsid.setVisible(false);
           sid.setVisible(false);
           del.setVisible(false);
        }
        else 
        {
           total.setEditable(true);
           lblsid.setVisible(true);
           sid.setVisible(true);
           del.setVisible(true);
           prid.setEnabled(false);
           prdesc.setEditable(false);
           custid.setEnabled(false);
           custdetails.setEditable(false);
           sve.setEnabled(false);
           ed.setText("Update");
        }
    }
    void getSidList()
    {
           sid.removeAllItems();
           sid.addItem("Select Sales Id");
           try
           {
              ResultSet rs = Admin.getSalesId();
              while(rs.next())
                  sid.addItem(rs.getString(1));
           }catch(Exception ex){}
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prid = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        prdesc = new javax.swing.JTextArea();
        qty = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        lblqty = new javax.swing.JLabel();
        custid = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        custdetails = new javax.swing.JTextArea();
        sve = new javax.swing.JButton();
        clr = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ed = new javax.swing.JButton();
        lblsid = new javax.swing.JLabel();
        sid = new javax.swing.JComboBox<>();
        del = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        paid = new javax.swing.JTextField();

        setBackground(new java.awt.Color(231, 222, 194));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Sales Form", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bradley Hand ITC", 1, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Product Id");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Product Desc");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Total Price");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Price");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Customer Id");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("Customer Details");

        prid.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        prid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pridItemStateChanged(evt);
            }
        });

        prdesc.setColumns(20);
        prdesc.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        prdesc.setRows(5);
        jScrollPane2.setViewportView(prdesc);

        qty.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        qty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                qtyFocusLost(evt);
            }
        });

        price.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        lblqty.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblqty.setText("Max Qty");

        custid.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        custid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                custidItemStateChanged(evt);
            }
        });

        custdetails.setColumns(20);
        custdetails.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        custdetails.setRows(5);
        jScrollPane1.setViewportView(custdetails);

        sve.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        sve.setText("Save");
        sve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sveActionPerformed(evt);
            }
        });

        clr.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        clr.setText("Cancel");
        clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setText("Quantity");

        ed.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ed.setText("Edit");
        ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edActionPerformed(evt);
            }
        });

        lblsid.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblsid.setText("Sales Id");

        sid.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        sid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sidItemStateChanged(evt);
            }
        });

        del.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setText("Paid Amount");

        paid.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(lblsid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prid, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(qty, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(total))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblqty)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(paid, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(custid, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 120, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(sve)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(del)))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsid)
                    .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(prid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblqty)
                            .addComponent(jLabel8)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(custid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sve)
                    .addComponent(clr)
                    .addComponent(ed)
                    .addComponent(del))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pridItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pridItemStateChanged
      try
      {  String ar[] = prid.getSelectedItem().toString().split("-");
         ResultSet rs = Admin.getSalesProductDetails(ar[0]); // 5 - Rin 250gm  (5
         if(rs.next())
         {
            prdesc.setText(rs.getString(1));
            maxqty = rs.getInt(2);
            lblqty.setText("Max Qty : "+maxqty);
            price.setText(""+rs.getDouble(3));
         }
      }catch(Exception ex){}
    }//GEN-LAST:event_pridItemStateChanged

    private void custidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_custidItemStateChanged
      try
      {  String ar[] = custid.getSelectedItem().toString().split("-");
         ResultSet rs = Admin.getSalesCustDetails(ar[0]); // 1 - Arif Chaudhary
         if(rs.next())
         {
            custdetails.setText("Contact No : "+rs.getString(1)+"\n"+rs.getString(2));
         }
      }catch(Exception ex){ }
 
    }//GEN-LAST:event_custidItemStateChanged

    private void qtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtyFocusLost
        
       int q = Integer.parseInt(qty.getText());
       String ar[] = lblqty.getText().split(":");
       maxqty = Integer.parseInt(ar[1].trim());
       if(q>maxqty)
       {
         int x = JOptionPane.showConfirmDialog(this, "You have Less Quantity in Stock to ur Sales Quantity,want to Sale out","Sales Quantity Confirm Dialog",JOptionPane.YES_NO_OPTION);
         if(x==1)
           qty.requestFocus(); // focus on qty.
       }
       double pr = Double.parseDouble(price.getText());
       total.setText(""+(q*pr));
       updqty = Integer.parseInt(qty.getText());
       currqty=0;
       currqty = prevqty - updqty;
       //  JOptionPane.showMessageDialog(this, "prev - "+prevqty+" , updqty - "+updqty+" , "+currqty);
       double prevprice = prevqty*(Double.parseDouble(price.getText()));
       double currprice = updqty*(Double.parseDouble(price.getText()));
       double paidamt = currprice-prevprice;
       paid.setText(""+paidamt);
      
    }//GEN-LAST:event_qtyFocusLost

    private void sveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sveActionPerformed
       String ar[] = prid.getSelectedItem().toString().split("-");
       String custInfo = custid.getSelectedItem().toString()+"\n"+custdetails.getText();
       String msg = Admin.addSales(ar[0],ar[1],prdesc.getText(),qty.getText(),price.getText(),total.getText(),custInfo,paid.getText());
       JOptionPane.showMessageDialog(this, msg);
       clear();
    }//GEN-LAST:event_sveActionPerformed

    private void edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edActionPerformed
       if(ed.getText().equals("Edit"))
       {
           lblsid.setVisible(true);
           sid.setVisible(true);
           del.setVisible(true);
           ed.setText("Update");
           sid.removeAllItems();
           sve.setEnabled(false);
           prid.setEnabled(false);
           prdesc.setEditable(false);
           custid.setEnabled(false);
           custdetails.setEditable(false);
           sid.addItem("Select Sales Id");
           try
           {
              ResultSet rs = Admin.getSalesId();
              while(rs.next())
                  sid.addItem(rs.getString(1));
           }catch(Exception ex){}
       }
       else
       {
           String ar[] = prid.getSelectedItem().toString().split("-");
           String custInfo = custid.getSelectedItem().toString()+"\n"+custdetails.getText();
           String msg = Admin.updSales(sid.getSelectedItem().toString(),ar[0],ar[1],prdesc.getText(),qty.getText(),currqty,price.getText(),total.getText(),custInfo,paid.getText());
           JOptionPane.showMessageDialog(this, msg);
           clear();
           lblsid.setVisible(false);
           sve.setEnabled(true);
           sid.setVisible(false);
           del.setVisible(false);
           prid.setEnabled(true);
           prdesc.setEditable(true);
           custid.setEnabled(true);
           custdetails.setEditable(true);
           ed.setText("Edit");
           prevqty = 0;
       }
    }//GEN-LAST:event_edActionPerformed

    private void sidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sidItemStateChanged
       try
       {
          ResultSet rs = Admin.getSales(sid.getSelectedItem().toString());
          if(rs.next())
          {
             prid.setSelectedItem(rs.getString(2)+" - "+rs.getString(3).trim());
             prdesc.setText(rs.getString(4));
             qty.setText(rs.getString(5));
             prevqty=rs.getInt(5);
             lblqty.setText("Max Qty : "+(maxqty+prevqty));
             price.setText(rs.getString(6));
             total.setText(rs.getString(7));
             String ar[] = rs.getString(8).split("\n");
             custid.setSelectedItem(ar[0]);
             
          }
       }catch(Exception ex) {}
    }//GEN-LAST:event_sidItemStateChanged

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "Do You want to Cancelled this sales.\n Total Return Amount is - "+(Double.parseDouble(qty.getText()) * Double.parseDouble(price.getText())));
        if(x==0)  
        {
            String msg = db.Admin.delSales(sid.getSelectedItem().toString(), prid.getSelectedItem().toString(),qty.getText());
            JOptionPane.showMessageDialog(this, msg);
            getSidList();
            clear();
        }
        else if(x==1)
        {
            clear();
        }
        
    }//GEN-LAST:event_delActionPerformed

    private void clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrActionPerformed
        inter.dispose();
    }//GEN-LAST:event_clrActionPerformed
    void clear()
    {
        prid.setSelectedIndex(0);
        price.setText("0");
        qty.setText("0");
        lblqty.setText("Max Qty : ");
        custid.setSelectedIndex(0);
        sid.setSelectedIndex(0);
        prdesc.setText("");
        custdetails.setText("");
        total.setText("0");
        paid.setText("0");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clr;
    private javax.swing.JTextArea custdetails;
    private javax.swing.JComboBox<String> custid;
    private javax.swing.JButton del;
    private javax.swing.JButton ed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblqty;
    private javax.swing.JLabel lblsid;
    private javax.swing.JTextField paid;
    private javax.swing.JTextArea prdesc;
    private javax.swing.JTextField price;
    private javax.swing.JComboBox<String> prid;
    private javax.swing.JTextField qty;
    private javax.swing.JComboBox<String> sid;
    private javax.swing.JButton sve;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
