/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Agile
 */
public class SalesmanReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesmanReportPanel
     */
    DefaultTableModel m = new DefaultTableModel();
    public SalesmanReportPanel() {
        initComponents();
             initComponents();
        try
        {
            ResultSet rs = Admin.getCustomerReport();
            ResultSetMetaData mt = rs.getMetaData();
            for(int i=1;i<=mt.getColumnCount();i++)
                m.addColumn(mt.getColumnName(i));
            String ar[];
            while(rs.next())
            {
               ar = new String[mt.getColumnCount()];
               for(int i=0;i<mt.getColumnCount();i++)
                   ar[i] = rs.getString(i+1);
               m.addRow(ar);
            }
        }catch(Exception ex){}    
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();

        jScrollPane1.setBackground(new java.awt.Color(230, 208, 164));

        tab.setBackground(new java.awt.Color(229, 214, 157));
        tab.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tab.setModel(m);
        jScrollPane1.setViewportView(tab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
